SAMPLE_DATA = [
    {
        "file_name": "outward_supplies_ledger_format.csv",
        "invoices": [
            {
                "Date": "01-04-2018",
                "Particulars": "Supplier name",
                "Type": "Taxable",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 0,
                "Central Tax": 6091.65,
                "State Tax": 6091.65,
                "Total Tax": 12183.30,
                "Rate": 0.18,
                "Month": "Apr-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Type": "Reversals",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 0,
                "Central Tax": 6091.65,
                "State Tax": 6091.65,
                "Total Tax": 12183.30,
                "Rate": 0.18,
                "Month": "Apr-18",
            },
            {
                "Date": "01-05-2018",
                "Particulars": "Supplier name",
                "Type": "Exempted",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "FALSE",
                "Invoice Value": 67685.00,
                "Taxable": 67685.00,
                "Integrated Tax": 0,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 0,
                "Rate": 0,
                "Month": "May-18",
            },
            {
                "Date": "01-05-2018",
                "Particulars": "Supplier name",
                "Type": "Reversals - Exempted",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "FALSE",
                "Invoice Value": 67685.00,
                "Taxable": 67685.00,
                "Integrated Tax": 0,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 0,
                "Rate": 0,
                "Month": "May-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Type": "RCM - Inwards",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 0,
                "Central Tax": 6091.65,
                "State Tax": 6091.65,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
        ],
    },
    {
        "file_name": "inward_supplies_ledger_format.csv",
        "invoices": [
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Expense Type": "Reverse Charge",
                "Type": "Reverse Charge",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 0,
                "Central Tax": 6091.65,
                "State Tax": 6091.65,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Expense Type": "Import",
                "Type": "Import",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 12183.30,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Expense Type": "Printing & Stationery",
                "Type": "Others",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 12183.30,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Expense Type": "Purchases",
                "Type": "Reversals - Rules",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 12183.30,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Expense Type": "Purchases",
                "Type": "Reversals - Others",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 12183.30,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
            {
                "Date": "04-04-2018",
                "Particulars": "Supplier name",
                "Expense Type": "Purchases",
                "Type": "Ineligible",
                "GSTIN/UIN": "09BIOPA1154J1Z9",
                "Taxability": "TRUE",
                "Invoice Value": 79868.30,
                "Taxable": 67685.00,
                "Integrated Tax": 12183.30,
                "Central Tax": 0,
                "State Tax": 0,
                "Total Tax": 12183.30,
                "Rate": 0.05,
                "Month": "Apr-18",
            },
        ],
    },
]
