basic_data_heading_map = {
    "gstin": "GSTIN",
    "fp": "Month",
}

b2b_heading_map = {
    "inum": "Invoice Number",
    "pos": "Place of Sale",
    "chksum": "Check Sum",
    "itms_0_itm_det_iamt": "IGST",
    "inv_typ": "Invoice Type",
    "itms_0_itm_det_samt": "SGST",
    "itms_0_itm_det_txval": "Taxable Value",
    "ctin": "GSTIN",
    "cfs3b": "GSTR 3B",
    "rchrg": "Reverse Charge",
    "itms_0_num": "Rate Number",
    "val": "Invoice Value",
    "itms_0_itm_det_camt": "CGST",
    "flprdr1": "GSTR 1 Filing Period",
    "itms_0_itm_det_csamt": "Cess",
    "fldtr1": "GSTR 1 Filing Date",
    "itms_0_itm_det_rt": "Rate",
    "idt": "Invoice Date",
    "cfs": "CFS",
    "dtcancel": "Date of Cancel(if)",
}

b2b_credit_notes_headings_map = {
    "inum": "Invoice Number",
    "nt_dt": "Credit Note Date",
    "itms_0_itm_det_camt": "CGST",
    "chksum": "Check Sum",
    "fldtr1": "Filing Date",
    "nt_num": "Credit Note Number",
    "val": "Invoice Value",
    "itms_0_num": "Rate Number",
    "idt": "Invoice Date",
    "ntty": "Credit Note Type",
    "itms_0_itm_det_iamt": "IGST",
    "itms_0_itm_det_samt": "SGST",
    "cfs3b": "GSTR 3B",
    "flprdr1": "Filing Period",
    "p_gst": "P GST",
    "itms_0_itm_det_txval": "Taxable Value",
    "cfs": "CFS",
    "itms_0_itm_det_rt": "Rate",
    "ctin": "GSTIN",
}

b2ba_heading_map = {
    "itms_0_itm_det_csamt": "Cess",
    "idt": "Invoice Date",
    "itms_0_itm_det_camt": "CGST",
    "chksum": "Check Sum",
    "inv_typ": "Invoice Type",
    "oinum": "Original Invoice Number",
    "fldtr1": "GSTR 1 Filing Date",
    "rchrg": "Reverse Charge",
    "itms_0_num": "Rate Number",
    "itms_0_itm_det_txval": "Taxable Value",
    "cfs3b": "GSTR 3B",
    "itms_0_itm_det_iamt": "IGST",
    "ctin": "GSTIN",
    "val": "Invoice Value",
    "inum": "Invoice Number",
    "aspd": "Original Invoice Period",
    "itms_0_itm_det_rt": "Rate",
    "cfs": "CFS",
    "flprdr1": "GSTR 1 Filing Period",
    "oidt": "Old Invoice Date",
    "pos": "Place of Sale",
    "atyp": "Original Invoice Type",
    "itms_0_itm_det_samt": "SGST",
}